[package]
name = "ff-carl-cli"
version = "1.0.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ff-carl = "0.1.1"
clap = "3.0"